### ISSUE TITLE
Do backups via CLI

### ISSUE THREAD

**Issue by einarpersson** [lervag/apy#102]
Hi!

I'd like to control my backups via this CLI if possible, so that I can include it in my other backup scripts.

Can you add a subcommand to do a full export (including media files) as described [here](https://docs.ankiweb.net/backups.html)?

**Comment by lervag** [comment]
Sounds doable - I expect there are some relevant Anki api's for this. It would be nice to understand more how such a subcommand should work. Could you help me spec it up? Something like:

```
> apy backup
Please provide an export target!

> apy backup filename.colpkg
Backup was saved to filename.colpkg

> apy backup --include-media filename.colpkg
Backup with media files was saved to filename.colpkg
```

**Comment by einarpersson** [comment]
I think your suggestion looks good! Would fit my needs. 

(albeit I am not too knowledgeable about the anki api/db, I am just a happy user).

PS. I just discovered your project (this). Very excited. I am integrating it with a terminal ai-assistant using [aichat](https://github.com/sigoden/aichat) and my notes in obsidian (using [obsidian.nvim](https://github.com/epwalsh/obsidian.nvim))

**Comment by lervag** [comment]
> I think your suggestion looks good! Would fit my needs.

Great; I have a PR now (#103) that I'll probably merge soon. I think it should fit your needs.

> PS. I just discovered your project (this). Very excited. I am integrating it with a terminal ai-assistant using [aichat](https://github.com/sigoden/aichat) and my notes in obsidian (using [obsidian.nvim](https://github.com/epwalsh/obsidian.nvim))

Great, glad to hear it! I'm not a very advanced ai user myself, prefer to do things manually. Guess you could call me old...
