### ISSUE TITLE
How to use the Cloze model?

### ISSUE THREAD

**Issue by vinoff** [lervag/apy#106]
```
  # Note

model: Cloze
tags: 
deck: Testing

## Front

Testing {{c1::this}} and {{c2::this also}}.

## Back

What should I put here?
```

So, I am starting to use Cloze cards. How should I add them with Apy? What should I add in the `## Back `field? I looked for the answer in the README and Wiki but couldn't find anything..

**Comment by vinoff** [comment]
Edit. I see that it can just be left blank!

**Comment by lervag** [comment]
Yes, that's right. And that's not something specific to `apy`, but rather to Anki itself. In any case, glad you figured it out!
