### ISSUE TITLE
Allow Models to be modified

### ISSUE THREAD

**Issue by dufferzafar** [lervag/apy#12]
We could get to complicated schema modifications later.

But, for now, I just wanted to rename a few models.

**Comment by lervag** [comment]
I'm not sure I understand exactly what you mean. Feel free to specify this in more detail.

**Comment by dufferzafar** [comment]
I wanted to rename a few models that I had in Anki. 

So having something like: `apy model mv Basic-22px Basic` would rename models.

**Comment by lervag** [comment]
Ok, so for now: Implement `apy model mv OldModelName NewModelName`. Seems possible. I'll look into it when I get the time.

**Comment by lervag** [comment]
This should work now.
