### ISSUE TITLE
ImportError: cannot import name 'MediaSyncer' from 'anki.sync'

### ISSUE THREAD

**Issue by dufferzafar** [lervag/apy#13]
```
❯ apy add -t python -d Python -m Basic-22px

reverting to stock json

Traceback (most recent call last):
  File "/home/dufferzafar/.local/bin/apy", line 11, in <module>
    load_entry_point('apy==0.1', 'console_scripts', 'apy')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/apy/cli.py", line 5, in <module>
    from apy.anki import Anki
  File "/home/dufferzafar/.local/lib/python3.8/site-packages/apy/anki.py", line 10, in <module>
    from anki.sync import Syncer, MediaSyncer, RemoteServer, RemoteMediaServer
ImportError: cannot import name 'MediaSyncer' from 'anki.sync' (/usr/lib/python3.8/site-packages/anki/sync.py)
```

Haven't debugged this further. Perhaps anki has been updated? Not sure.

**Comment by lervag** [comment]
Which version of Anki are you on?

**Comment by dufferzafar** [comment]
```
❯ anki --help
reverting to stock json
usage: anki [OPTIONS] [file to import/add-on to install]

Anki 2.1.26

optional arguments:
  -h, --help            show this help message and exit
  -b BASE, --base BASE  path to base folder
  -p PROFILE, --profile PROFILE
                        profile name to load
  -l LANG, --lang LANG  interface language (en, de, etc)
```

**Comment by lervag** [comment]
There has been some quite significant changes to Anki which required me to update apy accordingly, thus I had to update apy to fix things. Can you make sure you've updated to most recent apy?

**Comment by dufferzafar** [comment]
oh, sorry, didn't know apy had been updated!

and now I seem to have forgotten how i installed apy

i thought pip install --upgrade apy would fix it, but nope, it installed some other random package.

**Comment by lervag** [comment]
I've not published apy that way, sorry. I think you've `git clone`d somewhere, so if you go there and do `git pull`, then something like `pip install .`, then things should work.

**Comment by dufferzafar** [comment]
No, looked at my history, i installed it via the python egg way, and reinstalling seems to be giving me an older version:

```
❯ pipx install git+https://github.com/lervag/apy.git#egg=apy
  installed package apy 0.2, Python 3.8.2
  These apps are now globally available
    - apy
done! ✨ 🌟 ✨

❯ apy --help
Traceback (most recent call last):
  File "/home/dufferzafar/.local/bin/apy", line 5, in <module>
    from apy.cli import main
  File "/home/dufferzafar/.local/pipx/venvs/apy/lib/python3.8/site-packages/apy/cli.py", line 6, in <module>
    from apy.anki import Anki
  File "/home/dufferzafar/.local/pipx/venvs/apy/lib/python3.8/site-packages/apy/anki.py", line 8, in <module>
    import anki
ModuleNotFoundError: No module named 'anki'
```

I know

**Comment by dufferzafar** [comment]
Well, the readme talks about a version `0.3` that is compatible with anki `2.1.26` but the setup.py file has version 0.2!

**Comment by lervag** [comment]
hah, good point; fixing immediately

**Comment by lervag** [comment]
I'm not very used to versioning my projects...

**Comment by dufferzafar** [comment]
Could you please add this line in your installation section of the readme as well:

`pipx install git+https://github.com/lervag/apy.git#egg=apy`

**Comment by lervag** [comment]
> Could you please add this line in your installation section of the readme as well:
> 
> `pipx install git+https://github.com/lervag/apy.git#egg=apy`

Perhaps, could you explain what this does?

**Comment by dufferzafar** [comment]
So, [pipx](https://github.com/pipxproject/pipx) is a tool that installs packages in their own separate virtualenv - so they don't mess with your systems main installation.

I install all my tools using pipx.

Now, if you'd released it on PyPI, then it would be as simple as: `pipx install anki-apy`

But, now, we just use the github repo, the `git+https` and `#egg=apy` is just pip's syntax for doing the same.

**Comment by lervag** [comment]
Ah, I see. Thanks. Does this mean things are OK for you now?

**Comment by dufferzafar** [comment]
No no, you still have to update your `setup.py` 😃 

pipx is still installing an older version of this package that doesn't work!

**Comment by lervag** [comment]
I've just pushed `setup.py`, but the tag for `0.3` is not the same as the most recent tag. I've bumped to version 0.4. Does it work now?

**Comment by dufferzafar** [comment]
Yep! It worked!

And please don't include that pipx line. It won't work!

Reason being: `apy` requires `anki` so they both have to be in the same virtualenv.

This is what worked, finally: `pip install --user git+https://github.com/lervag/apy.git#egg=apy`

**Comment by dufferzafar** [comment]
Thanks for your prompt response @lervag!

**Comment by lervag** [comment]
No problem, thanks for the hints on `pip`. I've updated the readme again.
