### ISSUE TITLE
apy --help gives "Exception: couldn't find web folder"

### ISSUE THREAD

**Issue by ckp95** [lervag/apy#15]
I'm running Manjaro Linux. I installed `apy` using `pipx`. My anki is installed with `pacman`, but the source wasn't in `/usr/share/anki/`. Instead it looks as though it's in `/usr/lib/python3.8/site-packages/` -- at least, there are directories for `anki`, `aqt`, and `ankirspy` in there. So I do `export APY_ANKI_PATH=/usr/lib/python3.8/site-packages/`

However when I run `apy --help` I get this output:

    reverting to stock json
    Traceback (most recent call last):
      File "/home/ckp95/.local/bin/apy", line 5, in <module>
        from apy.cli import main
      File "/home/ckp95/.local/pipx/venvs/apy/lib/python3.8/site-packages/apy/cli.py", line 6, in <module>
        from apy.anki import Anki
      File "/home/ckp95/.local/pipx/venvs/apy/lib/python3.8/site-packages/apy/anki.py", line 10, in <module>
        from aqt.profiles import ProfileManager
      File "/usr/lib/python3.8/site-packages/aqt/__init__.py", line 35, in <module>
        from aqt.main import AnkiQt  # isort:skip
      File "/usr/lib/python3.8/site-packages/aqt/main.py", line 21, in <module>
        import aqt.mediasrv
      File "/usr/lib/python3.8/site-packages/aqt/mediasrv.py", line 31, in <module>
        _exportFolder = _getExportFolder()
      File "/usr/lib/python3.8/site-packages/aqt/mediasrv.py", line 28, in _getExportFolder
        raise Exception("couldn't find web folder")
    Exception: couldn't find web folder

I dug around in the `mediasrv.py` file and found this as the culprit function:

    def _getExportFolder():
        data_folder = aqt_data_folder()
        webInSrcFolder = os.path.abspath(os.path.join(data_folder, "web"))
        if os.path.exists(webInSrcFolder):
            return webInSrcFolder
        elif isMac:
            dir = os.path.dirname(os.path.abspath(__file__))
            return os.path.abspath(dir + "/../../Resources/web")
        else:
            raise Exception("couldn't find web folder")

    _exportFolder = _getExportFolder()

I stuck a `print(data_folder)` debug statement in there and ran `apy --help` again, this is what I got:

    /usr/lib/python3.8/site-packages/aqt/../aqt_data

Any idea how to fix?

**Comment by lervag** [comment]
What happens if you run `python`, then in the interactive REPL:

```sh
from aqt.profiles import ProfileManager
```

Does Anki itself work as expected?

Personally, I run Arch Linux, and since Manjaro is a derivative, I would think it should be quite straightforward to make apy work for you too.

By the way, see [this comment](https://github.com/lervag/apy/issues/13#issuecomment-631948678) in #13. It seems you should avoid `pipx` for this particular project.

**Comment by ckp95** [comment]
I get this:

    Python 3.8.3 (default, May 17 2020, 18:15:42) 
    [GCC 10.1.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from aqt.profiles import ProfileManager
    reverting to stock json
    /usr/share/aqt_data

**Comment by ckp95** [comment]
Maybe it's relevant: I'm using `pyenv` to manage my Python installs. When I run Python in the terminal I think it launches a different interpreter than the one pacman uses, maybe that's why it can't find the anki package. I'll investigate tomorrow.

**Comment by lervag** [comment]
> Maybe it's relevant: I'm using pyenv to manage my Python installs. When I run Python in the terminal I think it launches a different interpreter than the one pacman uses, maybe that's why it can't find the anki package. I'll investigate tomorrow.

Yes, definately. And I think that's sort of the point made in #13 

Essentially, of course, I think you can use apy within a python virtual environment, but then you need to make sure that anki itself is properly available within that environment. I'm not sure exactly how to create a virtualenv that also includes one or more system libraries, though.

**Comment by ckp95** [comment]
I'll try symlinking them

**Comment by ckp95** [comment]
Nevermind, I just installed it on my system Python rather than a `pyenv` one. I'm not happy with this solution but it does work.

**Comment by lervag** [comment]
> I'm not happy with this solution but it does work.

Sorry about that! If you find a way to make this work reliably when installed in a venv, then please let me know!
