### ISSUE TITLE
Problem with adding cards

### ISSUE THREAD

**Issue by skervim** [lervag/apy#2]
I finally found some time to try creating cards with `apy`.

When I try to type `apy add` into the terminal, my editor opens with: 
```
model: Basic
tags: marked

# Note

## Front

## Back
**CATEGORY**

## Hint
```
I change it to: 

```
model: Basic
tags: marked

# Note

## Front
What is this?
## Back
This is a test!

## Hint
test

```
When I exit my editor, the following error occurs:
```
Database was modified.
Remember to sync!
Traceback (most recent call last):
  File "/home/skervim/anaconda3/envs/rl/bin/apy", line 11, in <module>
    load_entry_point('apy', 'console_scripts', 'apy')()
  File "/home/skervim/anaconda3/envs/rl/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/skervim/anaconda3/envs/rl/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/skervim/anaconda3/envs/rl/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/skervim/anaconda3/envs/rl/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/skervim/anaconda3/envs/rl/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/skervim/apy/apy/cli.py", line 58, in add
    notes = a.add_notes_with_editor(tags, model)
  File "/home/skervim/apy/apy/anki.py", line 291, in add_notes_with_editor
    return self.add_notes_from_file(tf.name)
  File "/home/skervim/apy/apy/anki.py", line 297, in add_notes_from_file
    tags)
  File "/home/skervim/apy/apy/anki.py", line 324, in add_notes_from_list
    note['markdown']))
  File "/home/skervim/apy/apy/anki.py", line 354, in _add_note
    return Note(self, note)
  File "/home/skervim/apy/apy/note.py", line 11, in __init__
    self.fields = [x for x, y in self.n.items()]
  File "/home/skervim/anki/anki/notes.py", line 89, in items
    for ord, f in sorted(self._fmap.values())]
  File "/home/skervim/anki/anki/notes.py", line 89, in <listcomp>
    for ord, f in sorted(self._fmap.values())]
IndexError: list index out of range
```

Any idea what I am doing wrong?

**Comment by lervag** [comment]
Does you Basic note type have three fields? I would guess that the error is there because you are adding the third `Hint` field and that the `Basic` model does not support it. If this is so, then I would first open the Anki profile you are working with now and update the model accordingly.

Note: One weakness I've not documented right now is that the current version assumes you are using a single deck. I don't think this is relevant here, but I think it might be relevant to mention anyways.

**Comment by skervim** [comment]
Thanks for your answer. My `Basic` note type actually has a third `hint` field. 
I'm not yet sure why it didn't work. However, I tried it out a couple of times now, and sometimes it works, sometimes it doesn't. 
I also created a card for a different note type that I have. That worked mostly fine. 
I will give you an update when I have found out why it sometimes doesn't work. 

Have you considered to start writing a documentation? 

What is not completely clear to me: 
1) When I add a card with `apy add`, my editor (vim) opens. When I fill in the fields, do I need to save the buffer or can I just close it? 
2) Is there an option to abort the card creation after I have opened my editor with `apy add` ?

**Comment by lervag** [comment]
> Thanks for your answer. My Basic note type actually has a third hint field.
> I'm not yet sure why it didn't work. However, I tried it out a couple of times now, and sometimes it works, sometimes it doesn't.
> I also created a card for a different note type that I have. That worked mostly fine.
> I will give you an update when I have found out why it sometimes doesn't work.

Great, thanks. The project is currently (pre) alpha version in the sense that I only know that it works well for me. I would be happy to try to solve issues and make it work well for other people as well, but I have to admit that I'm not sure how to create a good "workflow" or "framework" for improving beyond my own usage. E.g., I now do some ad hoc testing, but developing a more robust version requires more robust testing. I'm not quite sure how to do that yet.

> Have you considered to start writing a documentation?

Yes. I've documented the command-line tool and tried to add all details necessary for the user of the tool. But I've not documented the code except for docstrings. And some comments.

I would much appreciate any assistance in improving things, and I'm very happy to help as much as I can. If you have suggestions for things that should be better documented, for instance, I'll be happy to oblige.

> 1. When I add a card with `apy add`, my editor (vim) opens. When I fill in the fields, do I need to save the buffer or can I just close it?

Yes, you must save and close (`:wq`). Closing without saving will not work. This should probably be mentioned somewhere.

> 2. Is there an option to abort the card creation after I have opened my editor with apy add ?

Yes, if you exit the editor with a non-zero exit code. In Vim, you can do `:cquit`.

**Comment by skervim** [comment]
Thanks for pointing out `:cquit`. Nice to learn something new! It's really time for me to work through vim's `user manual` once and for all :D . 
With the addition to the documentation, I think this issue can be closed.

**Comment by lervag** [comment]
> Thanks for pointing out :cquit. Nice to learn something new! It's really time for me to work through vim's user manual once and for all :D .

No problem. I'm actually working with the user manual myself (even though I've used Vim for 16-17 years already), and I find it very interesting to see that there are still things I've missed!

> With the addition to the documentation, I think this issue can be closed.

Great! I'll close when I've updated the usage section according to your later comment.

> When I have a bit more time on my hands I will look at the code and its documentation and see whether I can give some feedback about whether some documentation is missing.

Thanks! That will be very much appreciated!

> EDIT:
> Probably it would be a good idea to extend the usage section in the documentation,
>
> apy --help
>
> with some information about how to get information about the sub-commands, e.g.
>
> apy add --help
>
> At least I didn't get from the apy --help section that I would be able to give tags and model as options to the apy add command (which is by the way super awesome :) )

Good point. And thanks! :)
