### ISSUE TITLE
How do we edit notes & cards ?

### ISSUE THREAD

**Issue by AdrienLemaire** [lervag/apy#25]
Hi.

I'm having issues with Anki + Qt5 + Mozc + ibus + Wayland and from today cannot use Japanese within Anki anymore (or I'd have to write text in another window and constantly copy-paste over to the Anki browser).
I found apy as an alternative that would allow me to edit my cards/notes outside of Anki. Thanks for making it!

It's a bit unclear how I should be using apy thought.

Here's the flow I was expecting:
* `apy list -v <pattern>` should give me an id next to each match, that I can use in further queries
* `apy edit <id>` should open my editor (vim) and let me edit the card/note

But there doesn't seem to be a **edit** command yet ? :sweat_smile: 
Is it not possible to edit cards with apy ? :cold_sweat: 

Right now, when searching for cards, I see:
```console
$ apy list -v 名簿
reverting to stock json
Q: <div id="kard"> <div class="tags">KanjiInContext meaning:  名簿を作る時、日本ではあいうえお順、英語ではアルファベット順にする。   <script type="text/x-mathjax-config"> MathJax.Hub.processSectionDelay = 0; MathJax.Hub.Config({ me
A: <div id="kard">     <div class="tags" id='tags'>KanjiInContext     meaning:  名簿を作る時、日本ではあいうえお順、英語ではアルファベット順にする。            <div id='extra'>名簿・めいぼ・register / list of names 順・じゅん・order
ease: 250.0% lapses: 0 model: Basic

Q: <div id="kard"> <div class="tags">KanjiInContext reading:  <u>名簿</u>を作成する   <script type="text/x-mathjax-config"> MathJax.Hub.processSectionDelay = 0; MathJax.Hub.Config({ messageStyle:"none", showProce
A: <div id="kard">     <div class="tags" id='tags'>KanjiInContext     reading:  <u>名簿</u>を作成する            <div id='extra'>めいぼ・name roster, list of members  <script type="text/x-mathjax-config"> MathJax.Hub
ease: 250.0% lapses: 0 model: Basic

Q: <div id="kard"> <div class="tags"> <div id="cloze-content">名前を<span class=cloze>[reading 名簿]</span>・<u>戸籍</u>から<u>抹消</u>する  <script> const tags = document.getElementsByClassName("tags")[0].innerHTML.split(" ");
A: <div id="kard">     <div class="tags" id='tags'>     名前を<span class=cloze><u>名簿</u></span>・<u>戸籍</u>から<u>抹消</u>する            <div id='extra'>名簿・めいぼ・register/list of names 戸籍・こ
せき・census, family r
ease: 250.0% lapses: 0 model: Cloze

Q: <div id="kard"> <div class="tags"> <div id="cloze-content">名前を<u>名簿</u>・<span class=cloze>[reading 戸籍]</span>から<u>抹消</u>する  <script> const tags = document.getElementsByClassName("tags")[0].innerHTML.split(" ");
A: <div id="kard">     <div class="tags" id='tags'>     名前を<u>名簿</u>・<span class=cloze><u>戸籍</u></span>から<u>抹消</u>する            <div id='extra'>名簿・めいぼ・register/list of names 戸籍・こ
せき・census, family r
ease: 0.0% lapses: 0 model: Cloze

Q: <div id="kard"> <div class="tags"> <div id="cloze-content">名前を<u>名簿</u>・<u>戸籍</u>から<span class=cloze>[reading 抹消]</span>する  <script> const tags = document.getElementsByClassName("tags")[0].innerHTML.split(" ");
A: <div id="kard">     <div class="tags" id='tags'>     名前を<u>名簿</u>・<u>戸籍</u>から<span class=cloze><u>抹消</u></span>する            <div id='extra'>名簿・めいぼ・register/list of names 戸籍・こ
せき・census, family r
ease: 230.0% lapses: 1 model: Cloze
```
It's honestly hard to find out what is the card I'm looking for.
After some time reading the output, I understand that the top 2 questions are 2 Basic questions, and the bottom 3 are 1  Cloze question.
The cloze is the one I was looking forward to update.

Operations that I regularly do are:
* adding tags (using `randomize` tag to shuffle words in the question with a javascript snippet). apy has that covered, but using matching notes returns several results and I only want to target a single note.  I cannot seem able to use html tags in the query ? Allowing ids would be very handy.
    ```console
    $ apy list -v '前を<u>名簿</u>'
    reverting to stock json
    $ # nothing has been returned!
     ```
* Modifying notes content
* Converting a basic note to a cloze (assuming that if I could just edit the basic card, and replace its content with cloze content, it would be converted automatically like the Anki addon GODMODE ?)

Really hoping that either all of this is possible and I just missed something, or that you have a roadmap to include these features :heart:

**Comment by lervag** [comment]
I think what you're looking for is `apy review` (by default edits all _marked_ and _flagged_ notes). With `apy review -q "search-string"` you can edit notes that match the search string. I realize that the name of this command is not so good, as the word "review" has other connotations. The reason I called it "review" is that I consider a review of the contents of my notes, especially notes I've marked during my study sessions.

**Comment by AdrienLemaire** [comment]
@lervag this is pretty awesome :cupid: 
Maybe changing the description would be good enough. I indeed thought that this was about studying from the terminal ^^.
```diff
- Review marked notes (or notes that match
+ Edit marked notes (or matched query)
```
![](https://i.imgur.com/vqbNqpu.png)

You can close this issue whenever you want, I'll create a couple new ones now :)

**Comment by lervag** [comment]
Thanks. I've updated the help text and completion help text.

Happy you like it! :)
