### ISSUE TITLE
Display id and allow querying id

### ISSUE THREAD

**Issue by AdrienLemaire** [lervag/apy#26]
Given that a pattern can have several matches, it would be nice to see the id of the note in the `apy list` output, and use that id with `apy review` to edit a single note.

Quick look in the db shows that the associate column is called **cid**
```sqlite
sqlite> pragma table_info(notes);
cid  name   type     notnull  dflt_value  pk
---  -----  -------  -------  ----------  --
0    id     integer  0                    1
```

**Usage:**
```console
$ apy list -v 単語
Q: question 1 単語
A: answer 1
ease: 250.0% lapses: 0 model: Basic   id=1

$ API list -v 単語
Q: question 2 単語
A: answer 2
ease: 230.0% lapses: 0 model: Basic   id=2

...
$ apy review -i 2 
```

I'll admit that the feature is a low-priority, because it's quite easy to press `c` several time in the apy terminal editor until I reach the proper note, then `x` to abort.

**Comment by lervag** [comment]
Yes, good idea. `apy list -v` now shows the card ID (aka cid) for each card. The cid can be used with `apy review -q cid:ID`. But perhaps it is an idea to also add an option `apy review --cid CID`? And `apy review --nid NID`? (There's a difference between a note ID and a card ID.)

**Comment by AdrienLemaire** [comment]
oh, I didn't know that we could use the `cid:ID` query in Anki ^^ If it's covered, there's no need to create a new option for it.
Might be good to update the readme with a few examples though. This will prevent other users from making mistakes like me adding a space after the colon :)

Thanks for taking action so fast!

**Comment by lervag** [comment]
> oh, I didn't know that we could use the `cid:ID` query in Anki ^^ If it's covered, there's no need to create a new option for it.
> Might be good to update the readme with a few examples though. This will prevent other users from making mistakes like me adding a space after the colon :)

Done, added a few examples. Note that I've also added examples to some sub command help texts (e.g. `apy add-single -h`).

> Thanks for taking action so fast!

No problem, I appreciate getting input and feedback!
