### ISSUE TITLE
Review leeches

### ISSUE THREAD

**Issue by AdrienLemaire** [lervag/apy#29]
From https://github.com/lervag/apy/issues/25#issuecomment-690025819, it appears that `apy review` without query edits all marked and flagged notes.

Please consider also adding leeched cards in the default `apy review` :)  (`tag: leech`)

That brings another question. How can we query a tag with `apy list` ? tried `apy list 'tag: leech'` without success, and `apy list leech`  doesn't search in tags.

**Comment by lervag** [comment]
> From [#25 (comment)](https://github.com/lervag/apy/issues/25#issuecomment-690025819), it appears that `apy review` without query edits all marked and flagged notes.
> 
> Please consider also adding leeched cards in the default `apy review` :) (`tag: leech`)

I personally don't want that, but I agree it should be possible to specify it. Thus, I'll make it possible to specify the default in the config file.

> That brings another question. How can we query a tag with `apy list` ? tried `apy list 'tag: leech'` without success, and `apy list leech` doesn't search in tags.

You can't have a space there. Try `apy list 'tag:leech'`, it should work. Similar with `apy review -q 'tag:leech'`.

**Comment by lervag** [comment]
You can now specify the desired default query in your `~/.config/apy/apy.json` file. Let me know if this does not work as expected for you.

**Comment by AdrienLemaire** [comment]
@lervag works perfectly, thanks!

2 comments:
* Would be nice to keep the list of config options up to date in the readme
* Please consider following semver and properly version your releases. Your latest git tag is `v0.5.1` but installing with `pip install --upgrade --user git+https://github.com/lervag/apy.git#egg=apy` returns v0.6.0. And it looks like you just overwrote that version with your latest commit, instead of creating a new release. If I'm to make an AUR package (arch linux) for this tool, I need versions to be coherent (or to know that there's only one git master branch).

**Comment by lervag** [comment]
> @lervag works perfectly, thanks!

Great, happy to hear it!

> Would be nice to keep the list of config options up to date in the readme

Agreed and should be fixed now.

> Please consider following semver and properly version your releases. Your latest git tag is `v0.5.1` but installing with `pip install --upgrade --user git+https://github.com/lervag/apy.git#egg=apy` returns v0.6.0. And it looks like you just overwrote that version with your latest commit, instead of creating a new release. If I'm to make an AUR package (arch linux) for this tool, I need versions to be coherent (or to know that there's only one git master branch).

Ah, sorry. I do try to follow semver. The problem here is that I forgot to do `git push --tags`. One thing, though: I consider the untagged "tip" of the master branch as "in development", so I won't add new tags unless I feel confident that it is ready to "ship". I will probably bump the version after handling some of your issues. :)
