### ISSUE TITLE
Feature request: Support for multiple decks

### ISSUE THREAD

**Issue by skervim** [lervag/apy#3]
It would be great if there was support for multiple decks. 
For example, the syntax for creating a card with `apy add` in a deck called "Programming" could be:

```
deck: Programming
model: Basic
tags: marked

# Note

## Front

## Back

```

Currently it seems that cards are put into the deck that was last used.

**Comment by lervag** [comment]
Thanks for opening. I agree that support for multiple decks should be added, and I'll try and solve it. But I should first find a proper way to test features. Unless I find that this is "easy"...

**Comment by lervag** [comment]
Just to let you know: I've started to look at this now. It seems to be quite easy, so I think I will be able to add support for the "deck" syntax in not so long.

I'm not sure how to handle "implicit decks" though. That is, if one does not specify a deck at all, how should `apy` behave? Should it just silently use the active deck? (For me that would be fine.)

**Comment by skervim** [comment]
That's awesome to hear! 

In my opinion, it is okay for `apy` to silently (in the sense of "no confirmation required") use the active deck if no deck is explicitly chosen, but maybe it could inform the user with a print/logging statement about the chosen deck? Like: `print(f"No deck specified, writing to {deck_name}")`.

**Comment by lervag** [comment]
> In my opinion, it is okay for apy to silently (in the sense of "no confirmation required") use the active deck if no deck is explicitly chosen, but maybe it could inform the user with a print/logging statement about the chosen deck? Like: print(f"No deck specified, writing to {deck_name}").

Yes, that's a good idea. There is already an output that cards have been added, so I could just expand it to be verbose about where the cards are added. Thanks for the suggestion!

**Comment by lervag** [comment]
I think things work quite well now, and I would be happy if you could test.

Note, as before, please make sure to make backups!

**Comment by skervim** [comment]
I am very happy to read this! I will test it as soon as possible and report back, latest during the weekend. 
Unfortunately, I'm really swamped with work at the moment, otherwise I would also try to assist you on the programming site. When I have more time on my hands, I'll hope to be ably to help more!

**Comment by lervag** [comment]
No problem, I'm just happy to have more than myself interested in this. If you should get time and have an interest in assisting more, that's of course a bonus :)

In any case, in the meantime, I think I'll close this as it is _supposedly_ solved.
