### ISSUE TITLE
[Feat] Move note to deck

### ISSUE THREAD

**Issue by AdrienLemaire** [lervag/apy#33]
<details><summary>Not a bug: I forgot to use the `-d` option of `apy add`</summary>
When I try to add a new card to a sub-deck `Perso::JapaneseOther`, apy fails with the following error:

```console
➜ apy add
reverting to stock json
Traceback (most recent call last):
  File "/home/dori/.local/bin/apy", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/dori/.local/lib/python3.8/site-packages/apy/cli.py", line 116, in add
    notes = a.add_notes_with_editor(tags, model_name, deck)
  File "/home/dori/.local/lib/python3.8/site-packages/apy/anki.py", line 381, in add_notes_with_editor
    return self.add_notes_from_file(tf.name)
  File "/home/dori/.local/lib/python3.8/site-packages/apy/anki.py", line 385, in add_notes_from_file
    return self.add_notes_from_list(markdown_file_to_notes(filename),
  File "/home/dori/.local/lib/python3.8/site-packages/apy/convert.py", line 53, in markdown_file_to_notes
    defaults, notes = _parse_file(filename)
  File "/home/dori/.local/lib/python3.8/site-packages/apy/convert.py", line 154, in _parse_file
    note['fields'][field] = ''
KeyError: 'fields'
```
</details>

It doesn't appear possible to move existing cards to other decks. Can we have this feature supported? 

<img width=400 src="https://i.imgur.com/AygABWR.png" />

**Comment by lervag** [comment]
> Not a bug: I forgot to use the `-d` option of `apy add`
> When I try to add a new card to a sub-deck `Perso::JapaneseOther`, apy fails with the following error:

Although I agree it is not a bug, per se, perhaps this should have given a more informative error message? I'll look into it.

> ```
> ➜ apy add
> reverting to stock json
> ```

You can avoid that warning message if you intall `orjson` (the message is not from apy, but from Anki itself).

> It doesn't appear possible to move existing cards to other decks. Can we have this feature supported?

I think it is possible with the review feature, that is, by editing the cards one by one. But I guess you want a batch solution, similar to the `apy tag` feature?

It would help if you could describe how you think this should work. I don't use more than a single, large deck, so this is not a feature I'm personally interested in.

**Comment by AdrienLemaire** [comment]
> You can avoid that warning message if you intall orjson (the message is not from apy, but from Anki itself).

Thanks! Shouldn't it be a dependency of apy in the `setup.py`? 


> I think it is possible with the review feature, that is, by editing the cards one by one.

Actually, for my personal usage, I go one by one. 
How can I do this? I'm not seeing a `Move to deck` option in the review menu, and editing the note doesn't have any effect.
Here's a video demonstrating it:
[![apy review change model](https://i9.ytimg.com/vi/yZug3QbmsZU/mq2.jpg?sqp=CKyKgPsF&rs=AOn4CLCIYR3vhfAraSgGNZYTM-IQdCGIPw)](https://www.youtube.com/watch?v=yZug3QbmsZU&feature=youtu.be)

**Comment by AdrienLemaire** [comment]
> You can avoid that warning message if you intall orjson (the message is not from apy, but from Anki itself).

Thanks! Shouldn't it be a dependency of apy in the `setup.py`? 


> I think it is possible with the review feature, that is, by editing the cards one by one.

Actually, for my personal usage, I go one by one. 
How can I do this? I'm not seeing a `Move to deck` option in the review menu, and editing the note doesn't have any effect.
Or maybe you were saying "it is possible" as in "we could implement it" and not as "it's already working" ?

Here's a video demonstrating it:
[![apy review change deck](https://i9.ytimg.com/vi/M4W-Hl10tio/mq2.jpg?sqp=CNiMgPsF&rs=AOn4CLBmRtC-bIRTF7JA6JhD6jYxIuCdgg)](https://www.youtube.com/watch?v=M4W-Hl10tio&feature=youtu.be)


> I don't use more than a single, large deck, so this is not a feature I'm personally interested in.

I see :) I have only 2~3 top decks, but several layers of sub-decks. 
* Top decks help to divide the number of reviews in batches (doing 3 times 100 reviews is psychologically easier than 1 time 300 reviews).
* Sub-decks help me fine-tune my number of daily reviews / new cards by setting custom option groups (When the number of reviews becomes hardly manageable, I can reduce the number of cards in low-priority decks to make it easier).

It's great that Anki is so flexible we can use it however we like :)

> It would help if you could describe how you think this should work

I guess I'm fine with anything
* `apy move <cid> <Deck>`
* An option `m: Move to deck` in the review menu
* Modifying the model name from vim.

**Comment by lervag** [comment]
Sorry for not following up! I've been busy with a lot of things lately, and when I've had spare time I've devoted it for vimtex (I'm working on a relatively big new feature - native syntax highlighting). I've not forgotten about this and I will find time for it in the hopefully not too far future.

**Comment by lervag** [comment]
I've made a first version now. Not sure if you're still interested, but I think it is a useful feature nonetheless. It is now possible to edit the deck with the option `D: Change deck` in the review menu, as well as by changing the deck name from Vim while editing a note content.

I think this resolves the issue, but let me know what you think. Perhaps we should also add `apy move ...` or something similar to allow some sort of batch mode (similar to `apy tag`).

**Comment by AdrienLemaire** [comment]
Looks great, thanks a lot! I've burnt out last month and not studying much recently, but I'll get back to it eventually :)

**Comment by lervag** [comment]
> Looks great, thanks a lot!

No problem, thanks for the feature suggestion and sorry for taking all this time making it!

> I've burnt out last month and not studying much recently, but I'll get back to it eventually :)

Ah; Anki burnout is real. My only suggestion, in case you are interested, is to keep things slow. Don't add too many cards. Keep the review amount small enough so it does not become a burden. I guess the target amount is very subjective. I personally avoid having more than 100 cards per day to review, and I don't add more than between 25 and 75 cards per week.
