### ISSUE TITLE
images not shown

### ISSUE THREAD

**Issue by AdrienLemaire** [lervag/apy#35]
Pressing `f` from the editor menu doesn't change anything:

![](https://i.imgur.com/cwCbPvu.png)

When I try to reproduce what the code is supposed to do,

https://github.com/lervag/apy/blob/1ef31eb5c05c4c6e8c2f83cac292bf1830154c0e/apy/note.py#L139

I can display the image:

![](https://i.imgur.com/fmpPNl8.png)

On a side note, it'd be great if we could configure our image viewer in the settings.
I personally use [imv](https://github.com/eXeC64/imv) on wayland.

**Comment by lervag** [comment]
Haha, yes, sorry. You've got me. The `f` command was added initially to work with LaTeX figures. So it currently only works for these. I've been annoyed with this myself a couple of times, so I'll keep this issue open until I've improved it:

* [ ] Make `f` open all figures in a note, both `<img` tags and `LaTeX`.
* [ ] Allow to choose the image viewer(s) in your config (I currently use `display` for `svg` files and `feh` for image files).

**Comment by AdrienLemaire** [comment]
Thanks ! Yeah, I switched from feh to imv precisely for svg support ^^

**Comment by lervag** [comment]
Ok, I've made the required changes now, I think. Let me know what you think. Is the configuration understandable and does it look convenient? Do you have better suggestions for how to do this?

**Comment by AdrienLemaire** [comment]
@lervag works well, thanks!

**Comment by lervag** [comment]
Good to hear! :)
