### ISSUE TITLE
Show card type in apy list verbose

### ISSUE THREAD

**Issue by AdrienLemaire** [lervag/apy#37]
This is a follow-up to https://github.com/lervag/apy/issues/27#issuecomment-692378128 in #27.

![](https://i.imgur.com/USAY52B.png)

At the moment, unless there has been a lapse or the card's ease has been changed, there is no way to distinguish new cards from learnt ones.
If the card was already learnt, `apy reposition will fail`:
```console
$ apy reposition 0 tag:fixme
Can only reposition new cards!
Aborted!
```
But if I have dozen of cards in the query I'm trying to reposition,] it's very difficult to figure out which one is not new.

Could we see the current type of each cards in `apy list -v` ?
By card type, I mean seeing "unseen", "young", "mature" as shown in the stats.
![](https://i.imgur.com/530jgba.png)

**Comment by lervag** [comment]
> But if I have dozen of cards in the query I'm trying to reposition,] it's very difficult to figure out which one is not new.

Note, you can add `is:new` to your query. E.g. `apy reposition 0 tag:fixme is:new`.

> Could we see the current type of each cards in `apy list -v` ?

Yes, sure. And I guess we can add the stats for unseen, young, mature to the `apy info` screen as well.

**Comment by lervag** [comment]
Done.

**Comment by AdrienLemaire** [comment]
> Note, you can add is:new to your query. E.g. apy reposition 0 tag:fixme is:new.

How come I couldn't think of this one? :open_mouth: 

Thanks for the tip and commit!
