### ISSUE TITLE
markdown_models option not working

### ISSUE THREAD

**Issue by AdrienLemaire** [lervag/apy#38]
Added my sub-deck `Pro::IT / Tech` to the list of markdown models.
Expected: creating a card should show `markdown: true`
Actual: always seeing `markdown: false`

![](https://i.imgur.com/Lm0CWH9.png)

**Comment by lervag** [comment]
> Added my sub-deck `Pro::IT / Tech` to the list of markdown models.
> Expected: creating a card should show `markdown: true`
> Actual: always seeing `markdown: false`

I wonder: The markdown formatting is only applied for "non trivial" cards. Thus, if you simply write text without any formatting, it will _not_ be passed through the markdown converter. Would this explain your issue, or are you having this issue even for "complex" cards?

**Comment by lervag** [comment]
You strike me as quite competent, so I wonder if you would be able to do some personal debugging here. In the lines:

https://github.com/lervag/apy/blob/master/apy/anki.py#L364-L365

Could you add a `breakpoint()` here to investigate what might be happening? E.g., change the code to

```python
            breakpoint()
            if model_name not in cfg['markdown_models']:
                input_string += ['markdown: false']
```

which should start a debugger session when the code hits the `breakpoint()` in which you can investigate the content of `cfg['markdown_models']` and the value of `model_name` and with that try to understand if the `input_string += ...` is running as expected.

**Comment by AdrienLemaire** [comment]
@lervag sorry about that, I made you lose your time :(  I had confused model names with deck names.

```py
ipdb> cfg['markdown_models']
['Pro::IT / Tech']
ipdb> model_name
'Basic'
```

Closing :bow:

**Comment by lervag** [comment]
> @lervag sorry about that, I made you lose your time :( I had confused model names with deck names.

No problem, not much time was lost. And everyone makes mistakes, so no worries! :)
