### ISSUE TITLE
Feature Request: Imitate frozen field addon

### ISSUE THREAD

**Issue by skervim** [lervag/apy#4]
A very useful anki addon for the creation of cards with anki desktop is the [frozen field addon](https://ankiweb.net/shared/info/516643804). 
From its description: "Anki supports sticky fields. A sticky field is a field whose value is not deleted when you switch to a different note. This can be very useful if you are making many notes in which a field either has the same value or changes very little."

It would be awesome if there was a syntax to specify sticky fields for a markdown file from which we create anki cards via `apy add-from-file input.md`. 

Just like it is possible to specify the note type (model) for several notes in advance: 
```
        //input.md
        model: Basic
        tags: marked

        # Note 1
        ## Front
        Question?

        ## Back
        Answer.

        # Note 2
        tag: silly-tag

        ## Front
        Question?

        ## Back
        Answer
    
```
it would be very useful to determine the value of certain fields for all notes in advance.

**Comment by skervim** [comment]
To show an exemplary use case. The standard note type I use instead of the default `Basic` note type is the following. 

```
snippet std "Anki note: Standard model" b
# Note

## Front
$2

## Context
$3

## Back
$4

## Remarks
$5

## Example
$6

## Source
$7

## Timestamp
`!v strftime("%Y-%m-%d %H:%M")`

$8
endsnippet
```

In this example, the `source` and `context` fields often have the same value for all the cards that I create within a creation session. If I could determine their value in the beginning of the file, like for instance 

```
model: Standard
tags:  topic::subtopic
## Context
Harry Potter and the Order of the Phoenix
## Source
https://en.wikipedia.org/wiki/Harry_Potter_and_the_Order_of_the_Phoenix
```
it would help to avoid a lot of duplicated effort.

**Comment by lervag** [comment]
I'm not sure about this. In the first versions, I did add some code to tailor things to my workflow, but I realized that it should rather be added to my Vim workflow and that it would be better to keep `apy` quite generalized.

For instance, I've created [my own mapping in Vim](https://github.com/lervag/dotvim/blob/d4b3eff/personal/ftplugin/markdown.vim#L4) to quickly parse a simple list like this:

```
title
Q: Question 1
A: Answer 1
Q: Question 2
A: Answer 2
```

Into cards like this:

```md
# Note
tag: title
model: Basic

## Front
Question 1

## Back
Answer 1

# Note
tag: title
model: Basic

## Front
Question 2

## Back
Answer 2
```

My point is: you are asking for a very workflow specific feature that I think is equally easy to solve by adding some custom bindings in your editor.

-----

However, if we find a simple and precise syntax for your suggestion, then I might reconsider. Currently, I allow to set default values for tags, the model, and whether or not to use markdown in the lines above the first note. Perhaps we should generalize this stuff?

**Comment by skervim** [comment]
After having read your answer, I do agree that my proposed example is not a good general idea, however I still think that it would be useful for many users if something similar to the `frozen field` functionality could be achieved, at least for the `apy add` command.

In my experience anki user usually add cards in one of two ways:
1) Adding a single card for some useful knowledge that just came up
2) Adding several cards regarding some topic

For 1) `apy add` is sufficient as it is. 

For 2)  I would e.g. start with `apy add -t tag::subtag -m mymodel`, fill in the fields in the browser and exit (e.g. with `:wq` for vim). Now when I proceed with the next card, for many note model types it would helpful to have some/all fields filled with the previous note's field values. 
Maybe this could be achieved somehow with the `template` argument of the `add_notes_with_editor` function?

**Comment by lervag** [comment]
> In general, what is your/the proposed workflow to add many cards with apy within a session. Is there a faster way than: ...

Yes! Probably not documented well enough, though. So, instead of

```
apy add
fill in card 1
:wq

apy add
fill in card 2
:wq

apy add
fill in card 3
:wq
```

You can do:

```
apy add
fill in card 1, 2, and 3
:wq
```

`apy add` really does the same as `apy add-from-file`, except the file is created (temporarily) and opened directly by `apy`, then parsed when it is saved and closed. That is, `apy add` is equiavalent to creating some `new_notes.md` file and doing `apy add-from-file`.

What do you think, do you still find 2) to be necessary to improve?

**Comment by skervim** [comment]
Thank you for your answer! 
I don't think 2) needs to be improved at this point, but agree that the `frozen field` behavior can and possibly _should_ be implemented _outside_ of `apy`, probably within the editor of choice, or with external code.  
So please feel free to close this issue :)

**Comment by lervag** [comment]
Great! And of course, feel free to open new issues/feature suggestions :)
