### ISSUE TITLE
Database is NA/locked!

### ISSUE THREAD

**Issue by Aguscarpio** [lervag/apy#42]
I have followed the instructions but when I execute the apy command it returns the message:
Database is NA/locked!
Aborted

Anyone has been in the same situation? What can I do?

![image](https://user-images.githubusercontent.com/43018768/116822511-97115f00-ab55-11eb-8ef9-7c06b9787ba7.png)

**Comment by lervag** [comment]
Do you have Anki desktop open at the same time? Please close all other local Anki sessions (e.g. Anki desktop).

**Comment by Aguscarpio** [comment]
> Do you have Anki desktop open at the same time? Please close all other local Anki sessions (e.g. Anki desktop).

SOLVED!!!

**Comment by nathanbraun** [comment]
In case it helps anyone else —

I was running into this same issue, without Anki desktop open.  Turned out I had a version of Anki > 2.1.35, installing that took care of it.

**Comment by lervag** [comment]
I'll add support for more recent versions as they hit my own systems. I'm on Arch Linux where I currently have v2.1.35 installed. I would not be surprised if a newer version is released quite soon, and I will then have to update apy to be compatible with this new version.
