### ISSUE TITLE
Fixing a broken link to a personal vim configuration with 

### ISSUE THREAD

**Issue by bybor** [lervag/apy#45]
Hi!

Wiki page found here https://github.com/lervag/apy/wiki/Vim mentions *personalized snippets* pointing to https://github.com/lervag/dotvim/blob/master/personal/ftplugin/markdown.vim#L12-L17 which leads to 404.

Could you please update it?

Thanks!

**Comment by lervag** [comment]
Thanks, I've fixed it now!
