### ISSUE TITLE
`apy add-single` options not working

### ISSUE THREAD

**Issue by pietro14** [lervag/apy#46]
I am not able to add a single note with this command (as reported in the README):

`apy add-single -p preset "Question/Front" "Answer/Back"`

But if I run this, it works:

`apy add-single --deck <deck_name> "Question/Front" "Answer/Back"`

(Currently, I have just one profile and one deck)

Maybe the flag and the options have been changed and the README was not updated.

By the way, great library! I love it!

**Comment by lervag** [comment]
> I am not able to add a single note with this command (as reported in the README):
> 
> `apy add-single -p preset "Question/Front" "Answer/Back"`

Sorry, there's a bug here. The short option is `-s`. I should either change the short option to `-p` or change the docs. The `-p` option for `apy` is also used for `--profile` (e.g. in `apy -p ...`), which is probably the reason I decided to use `-s`.

I believe the simplest and best choice here is to fix the documentation and to keep the `-s`, so as to avoid a breaking change.

> By the way, great library! I love it!

Thanks! Glad to hear it! I still use this pretty much every week myself and find it invaluable for adding and modifying Anki notes more quickly.
