### ISSUE TITLE
Suggestion/Question : Text to cards parsers

### ISSUE THREAD

**Issue by rigobert9** [lervag/apy#49]
*I'm sorry to intrude in the issues section of the project, but I couldn't find a more appropriate public space to ask*

I've been recently interested in the possibility of parsing my notes into Anki cards to auto-generate them directly from text files (e.g. read an "historynotes.md" file, and generate Cloze cards for every date in the file), and I'd like to implement this in the same spirit as this utility. Would such an addition fit into the project, or if not, is there any way to use some parts of project directly to add this utility?
Thanks for your great work, this has been really useful in scripting, keep up the great work!

**Comment by lervag** [comment]
> _I'm sorry to intrude in the issues section of the project, but I couldn't find a more appropriate public space to ask_

No need to to be sorry. I don't mind issues being used this way.

> I've been recently interested in the possibility of parsing my notes into Anki cards to auto-generate them directly from text files (e.g. read an "historynotes.md" file, and generate Cloze cards for every date in the file), and I'd like to implement this in the same spirit as this utility. Would such an addition fit into the project, ...

Well, good question. I'm not entirely sure, because it is somewhat unclear exactly how this would work.

> or if not, is there any way to use some parts of project directly to add this utility?

I would think you could use the apy code to build this with a simple script. Something close to the current `apy add-from-file` code, here:

https://github.com/lervag/apy/blob/2e01c19f3a5d8858809ab9be25fa2513cf9ee660/apy/cli.py#L123-L131

You probably need some different/extra code, but as I'm not sure exactly what you want, it is hard to suggest something more concrete.

Perhaps you could explain what you want by showing a simple example of the workflow you are imagining?

> Thanks for your great work, this has been really useful in scripting, keep up the great work!

I'm glad you find it useful!

**Comment by rigobert9** [comment]
Thank you for the pointer to the code.
The workflow I'm trying to make would be to use a file of notes, and apply multiple rules (which amount to different regexes) to turn sentences in the text into Cloze cards. As an example, in an history note with the phrase :
```
Napoleon led the Grande Armée in Russia in 1812.
```
would produce, using the "proper noun" and "date" rules, the following card :
```
{{c1::Napoleon}} led the {{c2::Grande Armée}} in {{c3::Russia}} in {{c4::1812}}.
```

This way, I want to be able to parse files with normal notes, directly into cards.
I'm aware the idea is a bit personal and of inaccurate efficiency, which is why I wanted to ask where to put it first.

**Comment by ckp95** [comment]
Detecting things like proper nouns, different date formats, and whether to
include multiple words or not seems like it would be very complicated for
an automated script. Chances are you'd keep needing to go back and modify
it as new edge cases crop up. I think it would be a better approach to do
this in a semi-manual way: use some feature of your text editor to let you
highlight words and surround them with the cloze syntax quickly. Like use
vim macros or something. Then when every line is formatted how you want,
importing into anki is just a simple loop that invokes the usual apy
command.

**Comment by rigobert9** [comment]
That's indeed a better approach, as it would enable to add edge cases or remove false positives when writing, but that gets in my way in two ways :
- I'd like to keep my notes in a clean markdown format (that I can read later or render), and I don't want to add an extra step of reviewing (I wouldn't do it in a separate file before creating cards, as that would defeat the purpose of automating cards from my notes), even at the risk of needing to delete cards when using anki
- Most importantly, I have absolutely no idea on how to do this (I use vim/neovim), wouldn't that add a huge lot of overhead while writing (either for the writer or the editor) and be quite intrusive when writing ?

Thanks for the insight though, I will reflect upon this way of doing it that could be a great workflow if I think it through

**Comment by ckp95** [comment]
The automated approach is basically a whole natural language processing problem, I don't see how you're going to get around manual intervention. Plus, wouldn't it be useful for you anyway to know which parts of your notes got made into clozes? You could store your notes with a more minimal markup like this:

```
{Napoleon} led the {Grande Armée} in {Russia} in {1812}.
```

That's easier to type, easier on the eyes. Then so long as you don't use curly braces for anything else (I don't think they're used in standard markdown), you can have a very simple script that expands them into the full `{{c2::Grande Armée}}` syntax before feeding it into Anki.

You can use the `vim-surround` plugin to make it easier to surround words with braces.

**Comment by rigobert9** [comment]
I thought this would be bothering me in my approach, but I might as well just mark what I want to be made into a card with classic Markdown formatting, that would be a much better idea for both by notes and this automatic card-making, like :
```
__Napoleon__ led the __Grande Armée__ in __Russia__ in __1812__.
```
This way it could improve my notes, and enable marking only when relevant, without getting in my way, while also working with all markdown editors.

Thanks for your advice and insight, I'll definitely go with that.

As for apy, would a plugin such as this (creating cards from formatting like italic, bold and underlined) be relevant ? It shouldn't be too hard to do whether it's in your project directly or not, but I think this approach could benefit other people using this kind of utility.
Once again, thanks a lot for the insight and help for this matter, definitely opened my eyes in a much needed way before going back to taking notes !

**Comment by MagicJF** [comment]
A bit offtopic but worth mentionong.
Quality beats quantity, i rather prefear to put into long term memory a few good synthesized cards than a bunch of mediocre unstructurized stuff.
In that sense, you only build your cards once but review them many times, therefore might payoff to not rush and put love into the making process.

**Comment by rigobert9** [comment]
@MagicJF I thought about this too, but I'm mostly afraid to get sidetracked, because I'll certainly end up trying to write cards while listening to lessons or while reading my notes, leading me to either lack of concentration or losing the linearity of my reading. While I most definitely agree with you, I think this approach will allow me to put more attention on my notes rather than risking loss of information by trying to make atomic Anki notes as a primary objective

**Comment by lervag** [comment]
First, thanks for the insightful and good comments by @MagicJF and @ckp95!

> As for apy, would a plugin such as this (creating cards from formatting like italic, bold and underlined) be relevant ? It shouldn't be too hard to do whether it's in your project directly or not, but I think this approach could benefit other people using this kind of utility.

Well, it is still unclear exactly would "a plugin such as this" _is_. Perhaps it would be relevant, but to be sure I would need to understand properly _how_ it would work.

I mean, for instance: `apy` allows to add notes based on Markdown formatted files with `apy add-from-file`. So, it seems you are proposing something along the lines of `apy cloze-from-file` or similar that takes a file with some specified formatting and then adds cloze cards based on that. But, for this to be useful for others, you need to make things very specific/explicit. _How_ should the input file look? _What_ will be recognized as a single note? And so on.

If you propose something along these lines, and if it ends up working well, then I would not mind adding it to `apy`! But in the meantime, I believe it should be relatively easy to create something that relies on the current `add-from-file` capabilities in custom scripts. (Relatively is a key word, of course; it would be pretty simple for me, but it may be hard for anyone who is not familiar with Python/`apy` code/Anki code, and so on. I've tried to write `apy` in a readable and scriptable manner, but it doesn't mean I was successful :p)

(By the way, I don't think it is correct to use a space before punctuation in english. I notice you do that consistently, except for commas and dots?)

> A bit offtopic but worth mentionong. Quality beats quantity, i rather prefear to put into long term memory a few good synthesized cards than a bunch of mediocre unstructurized stuff. In that sense, you only build your cards once but review them many times, therefore might payoff to not rush and put love into the making process.

I agree with this sentiment. I don't use cloze cards at all. I don't mind adding a lot of very short cards, and I have some minor Vim macros and similar to facilitate my workflow. For me, quality is achieved through 1) atomicity - a card should have a single topic and a single, short answer, and 2) relevance! There should be some usefulness in memorizing a given fact. Quality is also improved by adding multiple cards for a topic/fact to make it easier to remember in various contexts. As a very basic example, I often make both backward and forward versions of most questions (but _not_ all). And I quite often add context questions to strengthen a particular fact.

----

By the way; I have a strict separation between my Anki collection and my notes. I write my notes in Markdown (or, a flavor of it) with my plugin wiki.vim. I do not try to memorize everything! I'm currently sitting on ~88000 lines of notes in my wiki, and it is not nearly possible to reflect that with Anki questions!

**Comment by rigobert9** [comment]
(As for punctuation, it's a bad habit of mine, I'm French and we always put a space before ! or ?, and I feel like it's more readable, thanks for pointing it out)
As for the workflow I thought up thanks to the advice from @ckp95, what I would envision is a simple way to make a Cloze on sentences with underlines, like
> ```
> __Napoleon__ led the __Grande Armée__ in __Russia__ in __1812__.
> ```
and maybe other simple rules like the generation of backward/forward cards from tables, such as
```
English | French
---|---
punctuation | ponctuation
```
This allows for the generation of cards only on relevant text, while also enhancing the notes themselves (anything you thought was important was underlined to make it into cards), while keeping up with good practices for anki cards.
This would indeed be very easy to make, especially using the code of apy, and I would be able to implement it myself for further testing.

**Comment by rigobert9** [comment]
I'm sorry I didn't get your question. The central idea behind all my struggle is to be able to work on "normal note" files, like your typical vimwiki page or markdown files (for an example of the notes I used to take with Obsidian, check my repository CoursTerminale, in "Histoire-géo/Histoire/Theme 2 La multiplication des acteurs internationaux dans un monde bipolaire/Chapitre 1 La fin de la seconde guerre mondiale et les debuts d'un nouvel ordre mondial.md").
My goal is then to use regexes to simply get sentences with some underlined text or tables like shown above to create cards.
For the end user, the process would simply be to:
- "naturally" take notes, while underlining interesting stuff to make into cards
- run `apy add-cloze-from-file history-08-25.md`
- get the created cards into a given deck
The rules followed by this formatting seem non-obstructive to me, and general enough to work for any kind of note.

**Comment by ckp95** [comment]
I think this is achievable with some fairly simple command line text
processing, I don't think it warrants a whole plugin. There might be an awk
or perl one-liner to do it.

**Comment by rigobert9** [comment]
I figured as much, I was considering doing it in a quick Perl script that would call apy in the shell, but I wanted to check here before to discuss it (I'm glad I did, you gave me most of the inspiration i needed to make something good) to ask if it was relevant enough to apy to be integrated for other users.

**Comment by rigobert9** [comment]
Then I'll try to do some lifting with regexes in Perl for the time being, and I'll come back with a first try and overview of what it can look like.
Thank all of you once again for your support and suggestions, this helped me seize my problem a lot better  before my classes start again. Have a great day!

**Comment by lervag** [comment]
Thanks; good luck! :)

**Comment by ckp95** [comment]
You could still put the script in the readme or on the wiki, that way it
would still be useful to others.

**Comment by lervag** [comment]
> You could still put the script in the readme or on the wiki, that way it would still be useful to others.

Yes, that's a good idea. I don't personally spend time on maintaining the wiki, but I would not mind adding some example scripts to the readme file.

**Comment by lervag** [comment]
No worries, and continued good luck with your studies!
