### ISSUE TITLE
Question: How to use latex math formulas in fields?

### ISSUE THREAD

**Issue by skervim** [lervag/apy#5]
How can I use latex math formulas within fields for `apy add` and `apy add-from-file`.
I could not find a recommended/working way in the documentation. 
However, writing formulas with latex is for many anki users an important feature during card creation.

**Comment by skervim** [comment]
Sorry, I didn't realize that I hadn't installed `dvipng` on a new machine, which led to the latex errors.
Apparently, I can just use the same latex markers as in anki desktop, e.g. `[$$] ... [/$$]`
Or is there a different recommended way for `apy`?

**Comment by lervag** [comment]
Yes, `apy` uses the same formatting as Anki in general with `[$$] ... [/$$]`, `[latex] ... [/latex]` and `[$] ... [/$]`. That is, `apy` does not really do anything but pass this directly to Anki.

Note: Right now, I've hardcoded some options for LaTeX. I plan to make this configurable, but have not done so yet. See [`apy/anki.py` line 17 and onwards](https://github.com/lervag/apy/blob/96b18b6/apy/anki.py#L17).

You can also write MathJax (see the Anki manual).

I'll leave the issue open until I've made the LaTeX options configurable.

**Comment by lervag** [comment]
I've added support for a config file at `~/.config/apy/apy.json`. See updated README for a description.
