### ISSUE TITLE
possible future problems with PEP 668

### ISSUE THREAD

**Issue by ckp95** [lervag/apy#53]
There's this [PEP 668](https://peps.python.org/pep-0668/). It's meant to stop people using pip to put stuff into the system Python environment and interfering with the distro package manager. It's probably a good thing for the Python ecosystem on net, because so much stuff gets silently broken when people do this. But I think it will cause problems for apy, at least the way it's set up now. The install instructions say to pip install it into the system Python environment so it can import the `anki` module, but that will no longer work when distributions adopt this PEP. Debian is already doing it, see [here](https://salsa.debian.org/python-team/packages/python-pip/-/blob/master/debian/NEWS).

Not sure what the solution would be other than mandating a virtual environment install. Perhaps resurrect the pipx idea from issue #20? pipx is apparently [recommended and maintained by the Python Packaging Authority](https://packaging.python.org/en/latest/key_projects/#pipx) nowadays, so this could be the way forward.

**Comment by lervag** [comment]
Good question! I'm also not sure what the proper solution is here. I guess user space is better than system space, at least, which is what we suggest in the current README.

I do agree `pipx` seems a good suggestion! When we have merged #56 and #57, then I guess we can do some proper testing that e.g. `pipx install git+https://github.com/lervag/apy.git#egg=apy` works? (Not sure if this will/should run in user space or system space?)

**Comment by ckp95** [comment]
User space for sure.

**Comment by lervag** [comment]
I'm sorry, but I don't really see exactly how to address this issue. Are you proposing any concrete changes, either to the code/build configuration or to the docs?

**Comment by ckp95** [comment]
I think it should be sufficient to recommend `pipx install github.com/...` in the README.

(also sorry for not following up on the other issues lately)

**Comment by ckp95** [comment]
yeah it just works!

```
pipx install git+https://github.com/lervag/apy
```

**Comment by lervag** [comment]
I believe we can close this, since #60 is merged?
