### ISSUE TITLE
Bug: note defaults override chosen model and tag types.

### ISSUE THREAD

**Issue by skervim** [lervag/apy#6]
I tried out the new code to test the multiple deck support. I found that here:
https://github.com/lervag/apy/blob/ec22f79962cb9a2792c822d4d99e563d6bda824e/apy/convert.py#L55-L60
the model type and tag type are overriden with the default types due to the `{**dict1, **dict2}` expression. I think a fix would be to switch the dictionaries in the expression: 
```
defaults = {**{"markdown": True, "model": "Basic", "tags": "marked"}, **defaults}
```

**Comment by lervag** [comment]
Thanks, good catch. Fixed now, and I've added a test for it as well.
