### ISSUE TITLE
`markdown_models` equivalent for `apy add-single`?

### ISSUE THREAD

**Issue by jrmallorca** [lervag/apy#67]
Hello, I was wondering if there was a `markdown_models` equivalent for `apy add-single`? I was surprised when I saw my flashcards not being formatted properly.

I'm currently not using `apy add-from-file` as `apy add-single` is more flexible for me. I can script it to detect a question and answer pair in a format I prefer.

**Comment by lervag** [comment]
> Hello, I was wondering if there was a `markdown_models` equivalent for `apy add-single`? I was surprised when I saw my flashcards not being formatted properly.

Good question. Could you give some explicit examples of how you foresee using this? I personally more or less never use `add-single`.

**Comment by jrmallorca** [comment]
Hello, sorry it took long for me to answer.

This is currently [the script I use with apy add-single](https://github.com/jrmallorca/dotfiles/blob/master/unix/scripts/add_flashcards_to_anki.sh).

I don't like using `apy add-from-file` as it would limit me to migrating all my flashcards into either 1 file or multiple files of all related flashcards. This wouldn't currently work with my structure of notes. I'd also have to do extra work in linking up where I got the idea of my flashcard from (i.e., its source).

With `apy add-single` it is much more flexible. More initial work, but it would allow me to migrate flashcards from my notes in a format I like. An example of a note I have that I would use my script on is something like:

<details open>
<summary>Note on the definition of comedogenic</summary>
<br>

```
# Comedogenic

The definition of comedogenic is "tending to clog pores especially by the formation of blackheads".

---

## References

- https://www.merriam-webster.com/medical/comedogenic

---

## Flashcards

What is the **meaning** of COMEDOGENIC? :: Tending to clog pores.
^1683667389270
```

</details>

**Comment by lervag** [comment]
Ok, let me see if I understand first. In your script, you have some markdown file as the argument `$1` where you first get some metadata like the tag and deck:

```sh
tags=$(get_tags_from_file $1)
deck=$(get_deck_from_file $1)
filename=$(basename "$1")
```

It seems the example you provide defines neither tags nor the deck, but these are probably easy details for you to handle. Now, further:

```sh
IFS=$'\n' && for qa_pair in $("$cat_cmd" "$1" | "$grep_cmd" " :: "); do
        question=${qa_pair% :: *}
        answer=${qa_pair#* :: }
        # …
done
```

Here you find each _line_ that has the string `" :: "` and you split it. The first part is considered the question, the second is considered the answer.

Now:

```
apy add-single \
        --preset "$APY_PRESET" \
        --deck "$deck" \
        --tags "$tags" \
        "$question" "$answer" "$filename"
```

Here you are using the `add-single` command more or less straightforwardly. The note type would have three fields, presumably.

If I understand correctly, the feature request is to allow for to use the markdown parser for the `"$question"` and the other fields. I think it should be quite easy to implement, but I think we should have it behind an option. E.g. `--parse-markdown`.

**Comment by jrmallorca** [comment]
Yes! That looks like it will do it. I'm unsure of how to test it out on my system by cloning the repo but it looks like that should do the trick.

One question though, did you mean to use an underscore for `--parse_markdown`?

**Comment by lervag** [comment]
> Yes! That looks like it will do it. I'm unsure of how to test it out on my system by cloning the repo but it looks like that should do the trick.

To test, you could do something like this:

```sh
mkdir test
cd test
python -m venv .venv
source .venv/bin/activate

# Install in a virtual environment from the specified feature branch
pip install git+https://github.com/lervag/apy@feat/add-single-markdown

# Now run apy
which apy # will show that we are using the temporary local version
apy add-single ...

# When you are finished testing you can safely remove the test folder!
cd ..
rm -rf test
```

> One question though, did you mean to use an underscore for `--parse_markdown`?

Thanks, good catch! I'll fix that. I've added tests that I think cover the new stuff, so I'll probably just merge this with the assumption that it works as expected. I believe it is a safe assumption.

**Comment by lervag** [comment]
Ok, I've merged it now.

**Comment by work-jrmallorca** [comment]
Just tested it through your instructions. It works as I want it to. Thank you so much!

**Comment by jrmallorca** [comment]
Just tested it like your instructions. It works in the manner I want it to. Thank you so much!
