### ISSUE TITLE
Usability: Create default config with `base_path` upon installation for convenience

### ISSUE THREAD

**Issue by cyrillkuettel** [lervag/apy#69]
Since the directory `Anki2` is the at a well-known location (only depends on the OS, correct me if I'm wrong), it can be guessed in 99% of cases, improving user experience. 

Let me know if you are interested in this, I'll implement and test this.

**Comment by lervag** [comment]
> Since the directory `Anki2` is the at a well-known location (only depends on the OS, correct me if I'm wrong), it can be guessed in 99% of cases, improving user experience.

Perhaps you are right. If you are, then I agree and would be very interested. :)

**Comment by lervag** [comment]
We are already looking at usual locations, though, see here:

https://github.com/lervag/apy/blob/68262ccd7c2ef77e12174a849d8d02267c1a8707/src/apy/config.py#L8-L19

I've pushed a PR for adding a similar standard path for MacOS. Is that what you are missing?

**Comment by cyrillkuettel** [comment]
Yes I was indeed on MacOS. Thanks for the quick response!

**Comment by lervag** [comment]
My pleasure!

Does this mean that #70 sufficiently resolves the issue?

**Comment by cyrillkuettel** [comment]
Absolutely. thanks

**Comment by lervag** [comment]
Great, glad to hear it!
