### ISSUE TITLE
Can apy be used to convert the contents of a markdown file to anki?

### ISSUE THREAD

**Issue by vinoff** [lervag/apy#82]
I am looking for something that I honestly think should not be hard:

- Convert a markdown file to anki cards.

Weirdly enough, I spend the whole morning trying many and none do what I want. I came across your posts on reddit and it left me wondering if apy does this..

Imagine I have a file, called input.md. This is a file which has all the cards I want. I edit this file with neovim, with my snippets and code completion and all that.

The file is something like this:

![apy](https://github.com/lervag/apy/assets/90382765/a788661a-9c46-4ca4-acd6-e90a46fb52ce)

The syntax itself does not really matter. I don't care if I separate cards using "---" or something else. Or if questions start with h1 headers or h2 headers or whatever. But hopefully you get the idea.

Then, I should be able to import the cards into anki.

Does apy does this?

**Comment by vinoff** [comment]
I just tried it and it does! Thank you so much @lervag!

**Comment by lervag** [comment]
> Does apy does this?

Well, yes, sort of. The Markdown syntax for notes is different than the one in your example.

> I just tried it and it does! Thank you so much @lervag!

It seems you figured it out; feel free to open issues to ask further questions or if you have problems.
