### ISSUE TITLE
Fallback to `$VISUAL` if `$EDITOR` is unset

### ISSUE THREAD

**Issue by camoz** [lervag/apy#86]
Hi!

What do you think about falling back to `$VISUAL` if `$EDITOR` is unset? Or even better, falling back to `$EDITOR` if `$VISUAL` is unset?

AIUI, `$VISUAL` would be the preferred way to specify terminal editors with "advanced" functionality:

https://unix.stackexchange.com/questions/4859/visual-vs-editor-what-s-the-difference

(Very low/no priority for me, just noticed it. I normally have `$EDITOR` unset.)

**Comment by lervag** [comment]
Thanks, that seems like a slight improvement, I agree. I've made the change now.
