### ISSUE TITLE
Changing a note type will fill in HTML and not markdown (even if it's semantically the same)

### ISSUE THREAD

**Issue by camoz** [lervag/apy#90]
I noticed that changing a note type will fill in the HTML and not the markdown in the new note, even if it's "semantically the same", i.e. the card has not been changed in Anki etc.

Is this intentional and perhaps difficult to achieve, or is it an oversight or regression?

(Btw, the idea of saving the markdown in the HTML data attribute and then comparing when editing the note is really neat!)

**Comment by lervag** [comment]
Sorry about the late response; the last few weeks I have been very busy.

> (Btw, the idea of saving the markdown in the HTML data attribute and then comparing when editing the note is really neat!)

Thanks - to be honest, the idea was stolen from an Anki addon. I don't remember quite which right now, but I liked it and "stole" it. ;)

> I noticed that changing a note type will fill in the HTML and not the markdown in the new note, even if it's "semantically the same", i.e. the card has not been changed in Anki etc.

Sorry, I think it's a bug - but I think it's fixed now.

**Comment by camoz** [comment]
Fix works here too, thanks!

**Comment by lervag** [comment]
Thanks, good to know!
