### ISSUE TITLE
`apy review` menu: Option/keybind to go back to the previous card

### ISSUE THREAD

**Issue by camoz** [lervag/apy#91]
In the `apy review` menu there is only a shortcut for going forward in the set of cards (`c`). How difficult would it be to implement a shortcut to go back to the previous card?

Use case: I added 20 cards today and want to modify one. I'm not sure, but I think the most straightforward way currently would be `apy review added:1` and then go to the card I'm looking for; with forward/backward this would be easier because with only forward I might miss the card and then have to start from the beginning.

PS: I'm starting to feel bad to open issues in your nice and clean issue tracker^^ Generally I'm very happy to contribute features myself (if they are approved of), but currently I'm quite busy with uni so it would have to wait a few months...

**Comment by lervag** [comment]
> In the `apy review` menu there is only a shortcut for going forward in the set of cards (`c`). How difficult would it be to implement a shortcut to go back to the previous card?

I would say _slightly_ difficult. Not very.

> Use case: I added 20 cards today and want to modify one. I'm not sure, but I think the most straightforward way currently would be `apy review added:1` and then go to the card I'm looking for;

Yes; you could also add more search terms, e.g. `apy review added:1 foobar`. Additional search terms will apply with the _and_ operator by default.

> with forward/backward this would be easier because with only forward I might miss the card and then have to start from the beginning.

Yes, I agree.

> PS: I'm starting to feel bad to open issues in your nice and clean issue tracker^^ Generally I'm very happy to contribute features myself (if they are approved of), but currently I'm quite busy with uni so it would have to wait a few months...

Don't worry about that! I'm very happy that someone is actually interested in the project and wants to contribute their thoughts and ideas! `apy` works well for me and my workflow, but input from people like you will likely improve the tool also for myself!

Clearly, I would prefer direct contributions in the form of PR's. But issues like those you are opening now are still much appreciated!

**Comment by lervag** [comment]
This is the "outer" logic for reviewing the cards:

https://github.com/lervag/apy/blob/bed7b887e84723415311e09f8bb9ff592d73c772/src/apyanki/cli.py#L385-L388

I think we would need to adjust the return value from the `.review` method. Perhaps something like this:

```python
# note.review → "continue" | "stop" | "rewind"

i = 0
number_of_notes = len(notes)
while i < number_of_notes:
    note = notes[i]
    status = note.review(i, number_of_notes)
    if status == "stop":
        break

    if status == "rewind":
        i = max(i - 1, 0)
    else
        i += 1
```

**Comment by lervag** [comment]
Ok; I've implemented the solution I suggested here. It's in `master` and will be part of the next release.
