### ISSUE TITLE
Question about markdown detection and LaTeX

### ISSUE THREAD

**Issue by camoz** [lervag/apy#92]
Markdown seems to be autodetected when adding a note via markdown files, e.g. `apy add`, but it can interfere with latex syntax.

For very simple latex it's fine I guess, but for more complex latex there is the risk that parts of it get interpreted as markdown and then become unusable. I have a few questions about this:

- Is there a way (right now) to exclude latex equations from markdown conversion? Perhaps I'm missing something...
- Would it make sense to modify the markdown detection such that fields get only interpreted as markdown if there is not any latex? I guess this is a minor issue since one can just turn on/off markdown explicitly via `markdown: false`.
- How do you personally handle this? Resort to HTML formatting when you have complex latex?

Side note: I think it's a bit unfortunate, albeit understandable, that Anki chose `\[\] \(\)` over `$/$$` delimiters. Because, the `$/$$` syntax is quite popular in markdown and is/will be supported by quite a few markdown tools. Btw there is a nice overview at the bottom of https://github.com/cben/mathdown/wiki/math-in-markdown

**Comment by lervag** [comment]
Hi! Just a heads up: I don't have time to answer right now; I've noticed you have several interesting and useful issues. I'm very happy to see someone interested in contributing like this, and I promise I will address them all. However, it might take a few days until I have the time to do so.

**Comment by camoz** [comment]
No worries! Take all the time you want and need of course. It's your project after all :) None of those issues are urgent for me, I'm just reporting on the fly what I find while I'm happily exploring apy.

But thanks for letting me know!

**Comment by lervag** [comment]
> None of those issues are urgent for me, I'm just reporting on the fly what I find while I'm happily exploring apy.

Great, and please continue to do so! If possible, I will be very happy to improve `apy` where possible (within my capacity and competence).

**Comment by lervag** [comment]
> For very simple latex it's fine I guess, but for more complex latex there is the risk that parts of it get interpreted as markdown and then become unusable. I have a few questions about this: …

To be honest, it's a little bit hard to answer here. It would be much easier to consider concrete examples of things that don't work as expected for you. Do you happen to have some examples?

Still, I'll try.

> * Is there a way (right now) to exclude latex equations from markdown conversion? Perhaps I'm missing something...

No, not really. But you can disable the markdown parsing alltogether with `markdown: false` in the note header.

> * Would it make sense to modify the markdown detection such that fields get only interpreted as markdown if there is not any latex? I guess this is a minor issue since one can just turn on/off markdown explicitly via `markdown: false`.

I'm not sure. I write plenty LaTeX and it works well for me. But I tend to write short and simple cards, so perhaps I've just not created something that
triggers the conflicts/problems you see?

> * How do you personally handle this? Resort to HTML formatting when you have complex latex?

As above: I don't really have any big problems. I mostly use one of two patterns, but I use both with Markdown.

* `[$$] equation [/$$]`
* `[latex] more advanced \LaTeX cards [/latex]`

In both cases, things generally work well on my end, even when the text is parsed with the Markdown parser.

> Side note: I think it's a bit unfortunate, albeit understandable, that Anki chose `\[\] \(\)` over `$/$$` delimiters. Because, the `$/$$` syntax is quite popular in markdown and is/will be supported by quite a few markdown tools.

Yes, I'll agree here. Although, Anki fields are HTML, not plain text or Markdown. Still, I think math in HTML could also be included with `$/$$` tags. And it would make more sense to use `<latex>...</latex>` instead of `[]` variants. I think.

In any case, you should notice the difference between the [MathJax support](https://docs.ankiweb.net/math.html#mathjax) and the [full LaTeX support](https://docs.ankiweb.net/math.html#latex). I _only_ use full LaTeX support, and (more or less) never the MathJax variant.

**Comment by lervag** [comment]
I'll close the issue - feel free to continue the discussion here and provide some examples of fields that don't work as you expect here or in new issues.

**Comment by camoz** [comment]
> It would be much easier to consider concrete examples of things that don't work as expected for you. Do you happen to have some examples?

To be honest it was more of a theoretical concern. I believe I have only crafted artificial examples in the past that don't make much sense anyway. I will just post again if I encounter any problems in day-to-day usage.

> In any case, you should notice the difference between the [MathJax support](https://docs.ankiweb.net/math.html#mathjax) and the [full LaTeX support](https://docs.ankiweb.net/math.html#latex). I only use full LaTeX support, and (more or less) never the MathJax variant.

Ahh I did not know that. I actually meant MathJax instead of LaTeX (though I guess there can be collisions with either one).

Small side note: Looks like with recent Anki versions, generation of LaTeX images *in Anki* is disabled by default, see https://github.com/ankitects/anki-manual/commit/09bff410a423a559e0be25eacdd6025f809be120 and https://github.com/ankitects/anki-manual/commit/fc8d1990238f1838615e7730c16717cbe029e061.

**Comment by lervag** [comment]
> > It would be much easier to consider concrete examples of things that don't work as expected for you. Do you happen to have some examples?
> 
> To be honest it was more of a theoretical concern. I believe I have only crafted artificial examples in the past that don't make much sense anyway. I will just post again if I encounter any problems in day-to-day usage.

👍

> > In any case, you should notice the difference between the [MathJax support](https://docs.ankiweb.net/math.html#mathjax) and the [full LaTeX support](https://docs.ankiweb.net/math.html#latex). I only use full LaTeX support, and (more or less) never the MathJax variant.
> 
> Ahh I did not know that. I actually meant MathJax instead of LaTeX

Ok!

> (though I guess there can be collisions with either one).

Not quite sure what you mean here. But I'll guess that you mean collision in the sense of the original post?

> Small side note: Looks like with recent Anki versions, generation of LaTeX images _in Anki_ is disabled by default, see [ankitects/anki-manual@09bff41](https://github.com/ankitects/anki-manual/commit/09bff410a423a559e0be25eacdd6025f809be120) and [ankitects/anki-manual@fc8d199](https://github.com/ankitects/anki-manual/commit/fc8d1990238f1838615e7730c16717cbe029e061).

Thanks for the heads up! I was not aware of this, and I would not be surprised if this will also affect `apy`.

**Comment by camoz** [comment]
> Not quite sure what you mean here. But I'll guess that you mean collision in the sense of the original post?

Yes, what I mean is that with Anki's delimiters for both MathJax and LaTeX syntax, there can be "collisions" like `*My formula*: \( 2*3*4 \)`, where, AIUI, `*3*` gets interpreted as italic in markdown, so it gets converted to HTML, and then Anki won't detect the MathJax anymore because there are HTML tags in it (that's my guess). But as you said, in practice it doesn't seem like a big deal.

**Comment by lervag** [comment]
Ah, yes, I see. Feel free to raise a new issue if you have a real case of this. If that happens, then I can see if I find a better way of avoiding this type of collision.

**Comment by jrotheneder** [comment]
I think I have an example of this kind of collision: 
```
# Note
model: Basic

## Front
Test 1

## Back
$\mathbb{R}_+$

# Note
model: Basic

## Front
Test 2  

## Back
$\mathbb{R}_+$
$\mathbb{R}_+$
``` 
produces the following output:

![Image](https://github.com/user-attachments/assets/9b8a3938-76ee-4ec5-beba-b8d503d4c8ad)

![Image](https://github.com/user-attachments/assets/031be10d-ac0f-4999-9035-b694493c87f7)

**Comment by lervag** [comment]
@jrotheneder Thanks! It would be very helpful if you could open a new issue here.
