### ISSUE TITLE
`apy info`: Note/card summary: Sum calculated wrong

### ISSUE THREAD

**Issue by camoz** [lervag/apy#97]
When printing statistics with `apy info`, the sum seems to be calculated wrong:

![sum](https://github.com/lervag/apy/assets/6276613/29647537-d81d-4ea9-a4a1-85efd653e379)

Both models I have are modified basic-reverse models. If you cannot notice this easily with your decks, let me know and I try to create a simple example.

**Comment by lervag** [comment]
Thanks. I've fixed this now. I'll probably make a release later today with the fix.

**Comment by camoz** [comment]
Thank you, works great!
