### ISSUE TITLE
Changing a note type does not detect current model

### ISSUE THREAD

**Issue by camoz** [lervag/apy#99]
When changing the model of a note via `apy review` -> `N`, the card's deck is not auto-detected for me, it will fill in `deck: Default` at the top of the vim buffer.

I've looked at the code (only for 5 minutes) but could not exactly figure it out how to fix it...

**Comment by lervag** [comment]
I don't use more than 1 deck myself, so this is probably something I've overlooked. I'll look into it when I get the time, probably later this week.

**Comment by lervag** [comment]
I believe it is fixed now in the latest push to master. Could you test it - i.e. use a local clone of `apy`, then either run `apy` inside with `poetry install` and `poetry run apy ...` or install it from master with `pipx install --force .` inside the repo. Let me know if you want more clear directions.

**Comment by camoz** [comment]
It works! Thank you!

**Comment by lervag** [comment]
Great, glad to hear it!
